server:
  port: 8080

spring:
  application:
    name: spring-gateway-service
    
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          include-expression: "'spring-database-service'.equals(serviceId)"
          
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:
        http://localhost:8761/eureka,http://localhost:8762/eureka,http://localhost:8763/eureka
      
management:
  endpoints:
    web:
      exposure:
        include: "*"